version: 2

sources:
  - name: dbt_seed
    database: dbt_teste
    schema: dbo
    freshness:
      warn_after: {count: 10, period: minute}
      error_after: {count: 5, period: minute}


    tables:
      - name: raw_payments
        loaded_at_field: created_at

      - name: raw_orders
        loaded_at_field: created_at

      - name: raw_customers
        loaded_at_field: created_at

